name: tezda_task_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  flutter_svg: ^2.0.10+1
  google_fonts: ^4.0.3
  device_preview: ^1.2.0
  connectivity_plus: ^5.0.2
  http: ^1.2.2
  fluttertoast: ^8.2.5
  flutter_secure_storage: ^7.0.1
  responsive_grid_list: ^1.4.0
  flutter_screenutil: ^5.9.3
  loading_gifs: ^0.3.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/svgs/
